### ISSUE TITLE
account.getTransactions Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by pradyumnad** [coinbase/coinbase-node#149]
Error Message:
```
code:"ESOCKETTIMEDOUT"
connect:false
message:"ESOCKETTIMEDOUT"
stack:"Error: ESOCKETTIMEDOUT\n    at ClientRequest.<anonymous> (/Users/dev/Sourcetree/beartax/backend/project/node_modules/coinbase/node_modules/request/request.js:813:19)\n    at Object.onceWrapper (events.js:277:13)\n    at ClientRequest.emit (events.js:189:13)\n    at ClientRequest.EventEmitter.emit (domain.js:441:20)\n    at TLSSocket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:277:13)\n    at TLSSocket.emit (events.js:189:13)\n    at TLSSocket.EventEmitter.emit (domain.js:441:20)\n    at TLSSocket.Socket._onTimeout (net.js:440:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
