### ISSUE TITLE
Error getting deposits list

### ISSUE THREAD

**Issue by ysilvela** [coinbase/coinbase-node#44]
I obtain this error when I call to getDeposits method:

TypeError: Cannot read property 'resource' of undefined
    at onGet (/var/lib/openshift/5562dcd5500446389000024c/app-root/runtime/repo/node_modules/coinbase/lib/model/AccountBase.js:61:62)
    at Request.onGet [as _callback] (/var/lib/openshift/5562dcd5500446389000024c/app-root/runtime/repo/node_modules/coinbase/lib/ClientBase.js:158:9)
    at Request.self.callback (/var/lib/openshift/5562dcd5500446389000024c/app-root/runtime/repo/node_modules/coinbase/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/lib/openshift/5562dcd5500446389000024c/app-root/runtime/repo/node_modules/coinbase/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/lib/openshift/5562dcd5500446389000024c/app-root/runtime/repo/node_modules/coinbase/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

And the code is:

		var client   = new coinbase.Client({'apiKey': clientAcc.KEY1, 'apiSecret': clientAcc.KEY2});
		client.getAccounts({}, function(err, accounts) {
		  accounts.forEach(function(acct) {
		    console.log('matchAccountTxWithRequests. Balance: ' + acct.balance.amount + ' para ' + acct.name);
		    	  var args = {
				    'colName'  : 'deposits',
				    'ObjFunc'  : Deposit,
				  };
		    	acct.getDeposits(args,function(err, txs) {
				  txs.forEach(function(txn) {
				    console.log('matchAccountTxWithRequests. txn details (' +  clientAcc.ClientId + ',' +  acct.name + ') : ' + JSON.stringify(txn));
				  });
				});
		  });
		});

Any Idea?

**Comment by manuel-di-iorio** [comment]
I confirm the issue.

And before the @ysilvela's error log, there is even: 
`var ObjFunc = self.client._stringToClass(result.data[0].resource);`

Pratically, the same bug as https://github.com/coinbase/coinbase-node/issues/37

**Comment by maksim-s** [comment]
Fixed here https://github.com/coinbase/coinbase-node/commit/288d1b708b6f175d10c00625835a2339d2d8e2fe
