### ISSUE TITLE
verifyCallback doesn't accept buffer from express body-parser verify

### ISSUE THREAD

**Issue by aristidesfl** [coinbase/coinbase-node#51]
It is not working after all.
The code:
```
app.post('/coinbase/notifications', bodyParser.json({ verify: function(req, res, buf) {
  if (!coinbaseClient.verifyCallback(buf, req.headers['X-Signature'])) {
    throw new Error('Coinbase notification did not verify');
  }
}}));
```
The error:
```
TypeError: Not a string or buffer
  at TypeError (native)
  at Verify.verify (crypto.js:307:23)
  at Base.Client.verifyCallback (/Users/user/Work/express/node_modules/coinbase/lib/Client.js:250:19)
  at verifyCoinbaseNotification (/Users/user/Work/express/src/app.coffee:17:18)
  at /Users/user/Work/express/node_modules/body-parser/lib/read.js:100:9
  at invokeCallback (/Users/user/Work/express/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
  at done (/Users/user/Work/express/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
  at IncomingMessage.onEnd (/Users/user/Work/express/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
  at emitNone (events.js:67:13)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)
```

**Comment by aristidesfl** [comment]
The header name needs to be lower case: `req.headers['x-signature'])`

**Comment by manuel-di-iorio** [comment]
You can close this issue now right?

**Comment by aristidesfl** [comment]
Right, sorry
