### ISSUE TITLE
json.parse not wrapped in try catch

### ISSUE THREAD

**Issue by EddieOne** [coinbase/coinbase-node#61]
Sometimes an html page is getting loaded instead of json as expected. Maybe the app is hitting a limit or it's proxy thing.

```
undefined:1
<!DOCTYPE html>
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at handleHttpError (/node_modules/coinbase/lib/errorHandler.js:43:38)
at Request.onGet [as _callback] (/node_modules/coinbase/lib/ClientBase.js:153:10)
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
