### ISSUE TITLE
"The transaction fee has expired" on all transactions

### ISSUE THREAD

**Issue by xanderdunn** [coinbase/coinbase-node#75]
coinbase-node 2.0.5

Every time I attempt to send BTC:
```
        account.sendMoney({
          to: payment.recipient,
          amount: payment.amount,
          fee: '0.0006',
          description: payment.note,
          currency: 'USD',
          idem: payment.idem
        }, cb)
```

I get this error:
```
 ValidationError: The transaction fee has expired.
     at handleHttpError (/app/node_modules/coinbase/lib/errorHandler.js:46:15)
     at Request.onPost [as _callback] (/app/node_modules/coinbase/lib/ClientBase.js:174:10)
     at Request.self.callback (/app/node_modules/coinbase/node_modules/request/request.js:344:22)
     at emitTwo (events.js:106:13)
     at Request.emit (events.js:191:7)
     at Request.<anonymous> (/app/node_modules/coinbase/node_modules/request/request.js:1239:14)
     at emitOne (events.js:101:20)
     at Request.emit (events.js:188:7)
     at IncomingMessage.<anonymous> (/app/node_modules/coinbase/node_modules/request/request.js:1187:12)
     at emitNone (events.js:91:20)
     at IncomingMessage.emit (events.js:185:7)
     at endReadableNT (_stream_readable.js:974:12)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I thought at first perhaps the transaction fee was too low, so I upped it from 0.0001 to 0.0006.  Also tried 0.0016.  Same result.

[Coinbase Status](https://status.coinbase.com/) is all green when this is happening.

**Comment by 2c2c** [comment]
do you mean .0006 usd or btc?

**Comment by xanderdunn** [comment]
It turns out this is simply because specifying a fee is no longer supported by the Coinbase API.  Coinbase automatically assigns the fee as of 21 March 2017.

**Comment by Inigovd** [comment]
Can this please be re-added to the API? Or a way to qoute what the fees will be? There is no way to send an exact amount of btc/eth using the API, which makes the entire API worthless to me...

Would love this!
