### ISSUE TITLE
Unable to import coinbase as angular module dependency

### ISSUE THREAD

**Issue by gdcrocx** [coinbase/coinbase-node#87]
I am trying to use the coinbase api v2 on ionic v1 framework but unable to import the coinbase library as an angular module dependency.

`angular.module('starter.controllers', [])

  .controller('DashCtrl', function ($scope) {

    var coinbase = '../../node_modules/coinbase/lib/Client'

    var client = new coinbase.Client({
      'apiKey': 'XXXXXXXXXXXX',
      'apiSecret': 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
      'version': '2017-08-18'
    });`

The browser throws up a "Not a constructor" error as shown below.

`TypeError: coinbase.Client is not a constructor
    at new <anonymous> (http://localhost:8100/js/controllers.js:11:18)
    at Object.instantiate (http://localhost:8100/lib/ionic/js/ionic.bundle.js:18015:14)
    at $controller (http://localhost:8100/lib/ionic/js/ionic.bundle.js:23417:28)
    at Object.self.appendViewElement (http://localhost:8100/lib/ionic/js/ionic.bundle.js:59908:24)
    at Object.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:57901:41)
    at Object.init (http://localhost:8100/lib/ionic/js/ionic.bundle.js:57821:20)
    at Object.self.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:59767:14)
    at Object.self.register (http://localhost:8100/lib/ionic/js/ionic.bundle.js:59725:10)
    at updateView (http://localhost:8100/lib/ionic/js/ionic.bundle.js:65400:23)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:65384:9 <ion-nav-view name="tab-dash" class="view-container tab-content" nav-view="active" nav-view-transition="ios">`

I did 
`angular.module('starter.controllers', ['coinbase'])` but it is not getting recognized.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
