### ISSUE TITLE
client.getNotifications always InternalServerError

### ISSUE THREAD

**Issue by ken-talkingsource** [coinbase/coinbase-node#90]
node version: 6.11.1
package version: 2.0.6

Every other function is fine, only **getNotifications** never works out!

```
// Simepl Test
const c = new Client({
    apiKey: COINBASE_API_KEY,
    apiSecret: COINBASE_API_SECRET
});
 c.getNotifications({}, (err, result, pagi) => {                                                                      
    if(err) { console.log(err); }                                                                                 
    console.log("nos is \n" + JSON.stringify(result));                                                               
}); 
```

and got InternalServerError:
```
InternalServerError: An error has occurred. If this problem persists, please message support@coinbase.com
    at handleHttpError (/root/mypath/node_modules/coinbase/lib/errorHandler.js:46:15)
    at Request.onGet [as _callback] (/root/mypath/node_modules/coinbase/lib/ClientBase.js:155:10)
    at Request.self.callback (/root/mypath/node_modules/coinbase/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/mypath/node_modules/coinbase/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/mypath/node_modules/coinbase/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
```

**Comment by ken-talkingsource** [comment]
Never mind, it's really an "Internal" server error.
I create a new coinbase account, use the same API setting & code,
everything works now.
The library is fine.
